# Site settings
title: BLOG
email: info@i2.si
copyright_name: Kailasa Partners Ltd.
future: true

# used to estimate reading time
wpm: 150

port: 4444
permalink: /:title

# jekyll-paginate
paginate: 5
paginate_path: /page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
